---
service: crime-data-api #name this whatever you want

package:
  exclude:
    - env/**

provider:
 name: aws
 runtime: python3.11
 region: us-east-1
 timeout: 300
 memorySize: 3008
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
 wsgi:
   app: handler.app
   packRequirements: false
functions:
 app:
   handler: wsgi_handler.handler
   layers:
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python311:3
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'
