---
service: crime-data-api #name this whatever you want
 
provider:
 name: aws
 runtime: python3.11
 region: us-east-1
 memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
 wsgi:
   app: handler.app
   packRequirements: false
functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'
